spring.application.name=streamlinecloud-backend

spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.url=jdbc:sqlite:streamlinecloud.db
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update

management.endpoints.web.base-path=/_server
management.endpoints.web.exposure.include=health,info,metrics

management.info.build.enabled=true
management.info.os.enabled=true
management.info.java.enabled=true

spring.rsocket.server.transport=websocket
spring.rsocket.server.mapping-path=/socket

springdoc.api-docs.enabled=true