name: StreamlineCloud
version: '${project.version}'
main: net.streamlinecloud.mc.PaperSCP
api-version: '1.20'
authors: [ Quinilo, creperozelot ]
description: This plugin needs to be installed on every server powered by StreamlineCloud
website: https://streamlinecloud.net/

commands:
  connect:
    description: Connect command!
  streamline:
    description: Streamline your server!
