name: Java Code Formatting Check

on: [push, pull_request]

jobs:
  check-formatting:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        module: ['streamlinecloud-api', 'streamlinecloud-main', 'streamlinecloud-mc']

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Install Checkstyle
      run: |
        wget -q https://github.com/checkstyle/checkstyle/releases/download/checkstyle-9.3/checkstyle-9.3-all.jar -O checkstyle.jar

    - name: Run Checkstyle on ${{ matrix.module }}
      continue-on-error: false
      run: java -jar checkstyle.jar -c /google_checks.xml ${{ matrix.module }}/src/ > checkstyle-result-${{ matrix.module }}.txt

    - name: Show Checkstyle Report for ${{ matrix.module }}
      run: cat checkstyle-result-${{ matrix.module }}.txt
